---
- hosts: all
  tasks:
    - name: remove docker container on host
      shell: |
         docker rm -f $(docker ps -a -q);
      
    - name: remove docker images from repository
      shell: |
         docker rmi -f $(docker images -a -q);
      
    - name: deploy docker application to host
      command:  docker-compose up --build -d